select*from EMP;

--1--
SET SERVEROUTPUT ON
DECLARE 
    V_SAL EMP.SAL%TYPE;
BEGIN 
    SELECT SUM(SAL)INTO V_SAL FROM EMP WHERE DEPTNO = 10;
    DBMS_OUTPUT.PUT_LINE('Pegawai dengan DEPTNO 10 memiliki gaji = ' || V_SAL);
END;
/

--2--
SET SERVEROUTPUT ON
DECLARE 
    V_NAME EMP.ENAME%TYPE;
BEGIN 
    SELECT ENAME INTO V_NAME FROM EMP WHERE SAL BETWEEN 900 AND 1000;
    DBMS_OUTPUT.PUT_LINE('Pegawai yang memiliki 
gaji diantar 900 dan 1000 adalah  ' || V_NAME);
END;
/

--3--
SET SERVEROUTPUT ON

ACCEPT V_NAME PROMPT 'MASUKKAN NAMA KARYAWAN:';
ACCEPT V_JOB PROMPT 'MASUKKAN JABATAN';
ACCEPT V_DEPTNO PROMPT 'MASUKKAN NOMOR DEPTNO';

DECLARE 
    V_EMPNO EMP.EMPNO%TYPE;
    V_SAL EMP.SAL%TYPE;
BEGIN
SELECT MIN(EMPNO)-10 , MAX(SAL)+250 INTO V_EMPNO, V_SAL FROM EMP;
    INSERT INTO EMP 
    (EMPNO,ENAME,JOB,SAL,DEPTNO) VALUES (V_EMPNO,'&V_NAME','&V_JOB',V_SAL,'&V_DEPTNO');
END;
/
select*from EMP;

--4--
SET SERVEROUTPUT ON
DECLARE 
    V_SAL EMP.SAL%TYPE := 200;
BEGIN 
    UPDATE EMP SET SAL = SAL +V_SAL WHERE DEPTNO >10;
END;
/

select*from EMP;

--5--
SET SERVEROUTPUT ON
DECLARE 
    V_JOB EMP.JOB%TYPE := 'CLERK';
    V_SAL EMP.SAL%TYPE := 1200;
BEGIN 
    DELETE FROM EMP WHERE JOB = V_JOB OR SAL <= V_SAL;
END;
/

select*from EMP;