--1--
CREATE TABLE MESSAGES_10119723 (RESULTS VARCHAR2(60));

DECLARE 
    I INTEGER;
BEGIN 
    FOR I IN 1..10 LOOP 
        IF (I <> 6) AND (I<>8) THEN 
            INSERT INTO MESSAGES_10119723 VALUES (I);
        END IF;
        END LOOP;
COMMIT;
END;

SELECT*FROM MESSAGES_10119723;

--2--
ALTER TABLE EMP ADD STARS VARCHAR2 (50);
DESC EMP;

--3--
SET SERVEROUTPUT ON 

DECLARE 
    X INTEGER; --MENYIMPAN HASIL
    I INTEGER ; --VARIABLE PERULANGAN PERTAMA
    J INTEGER ; --VARIABLE PERULANGAN KEDUA
    
BEGIN
    X:= 0 ; 
    FOR I IN 1..3 LOOP 
        FOR J IN 1..3 LOOP 
            X:= X+J ;
            DBMS_OUTPUT.PUT_LINE(X);
        END LOOP;
    END LOOP;
END;
/

--4--
SET SERVEROUTPUT ON 
ACCEPT BATAS PROMPT 'MASUKKAN BATAS PERULANGAN:';

DECLARE
    X INTEGER := &BATAS;
    Y INTEGER;
    
BEGIN 
    DBMS_OUTPUT.PUT_LINE('BILANGAN GANJIL');
    FOR Y IN 1..X LOOP
        IF (Y MOD 2) = 1 THEN 
            DBMS_OUTPUT.PUT_LINE(Y);
        END IF;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('BILANGAN GENAP');
    FOR Y IN 1..X LOOP
        IF (Y MOD 2) = 0 THEN
          DBMS_OUTPUT.PUT_LINE(Y);
        END IF;
     END LOOP;
        
END;